language: scala
scala: 
    - 2.10.6
    - 2.11.8
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-installer
branches:
    only:
        - master
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
