[package]
name = "rssidiot"
version = "0.1.0"
authors = ["Matthias Hansen <matthias.hansen@rwth-aachen.de>"]
[lib]
name = "rssidiot"
path = "src/lib.rs"
[[bin]]
name = "rssidiot"
path = "src/main.rs"

[dependencies]
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
